install texlive and cleanup

diff --git a/image/Dockerfile b/image/Dockerfile
--- a/image/Dockerfile
+++ b/image/Dockerfile
@@ -1,5 +1,5 @@
 FROM ubuntu:22.04
-MAINTAINER Josh A. Burns <josh@joshburns.xyz>
+LABEL maintainer="Josh A. Burns <josh@joshburns.xyz>"
 
 # APT Unattented installation mode
 ENV LANG=C.UTF-8
@@ -69,5 +69,90 @@ RUN echo "Preventing doc and man pages from being installed." &&\
     curl --output "/tmp/ttf-mscorefonts-installer.deb" "http://ftp.de.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.7_all.deb" &&\
     (apt install -f -y --no-install-recommends "/tmp/ttf-mscorefonts-installer.deb" || true) &&\
     rm -f "/tmp/ttf-mscorefonts-installer.deb" 
-    
-# TODO: Install texlive and ghostscript
+
+# Install texlive packages
+RUN echo "Installing Texlive and Ghostscript" &&\
+    apt-get install -f -y --no-install-recommends \
+          biber \
+          cm-super \
+          dvipng \
+          fonts-dejavu \
+          fonts-dejavu-core \
+          fonts-dejavu-extra \
+          ghostscript \
+          gnuplot \
+          make \
+          latex-cjk-all \
+          latex-cjk-common \
+          latex-cjk-chinese \
+          latexmk \
+          lcdf-typetools \
+          lmodern \
+          poppler-utils \
+          psutils \
+          purifyeps \
+          python3-pygments \
+          t1utils \
+          tex-gyre \
+          tex4ht \
+          texlive-base \
+          texlive-bibtex-extra \
+          texlive-binaries \
+          texlive-extra-utils \
+          texlive-font-utils \
+          texlive-fonts-extra \
+          texlive-fonts-extra-links \
+          texlive-fonts-recommended \
+          texlive-formats-extra \
+          texlive-lang-all \
+          texlive-lang-chinese \
+          texlive-lang-cjk \
+          texlive-latex-base \
+          texlive-latex-extra \
+          texlive-latex-recommended \
+          texlive-luatex \
+          texlive-metapost \
+          texlive-pictures \
+          texlive-plain-generic \
+          texlive-pstricks \
+          texlive-publishers \
+          texlive-science \
+          texlive-xetex \
+          texlive-bibtex-extra
+
+# delete Tex Live sources and other potentially useless stuff
+RUN echo "Delete TeX Live sources and other useless stuff." &&\
+    (rm -rf /usr/share/texmf/source || true) &&\
+    (rm -rf /usr/share/texlive/texmf-dist/source || true) &&\
+    find /usr/share/texlive -type f -name "readme*.*" -delete &&\
+    find /usr/share/texlive -type f -name "README*.*" -delete &&\
+    (rm -rf /usr/share/texlive/release-texlive.txt || true) &&\
+    (rm -rf /usr/share/texlive/doc.html || true) &&\
+    (rm -rf /usr/share/texlive/index.html || true)
+
+# update font cache
+RUN echo "Update font cache." &&\
+    fc-cache -fv
+
+# clean up all temporary files
+RUN echo "Clean up all temporary files." &&\
+    apt-get clean -y &&\
+    rm -rf /var/lib/apt/lists/* &&\
+    rm -f /etc/ssh/ssh_host_* &&\
+    echo "Delete man pages and documentation." &&\
+    rm -rf /usr/share/man &&\
+    mkdir -p /usr/share/man &&\
+    find /usr/share/doc -depth -type f ! -name copyright -delete &&\
+    find /usr/share/doc -type f -name "*.pdf" -delete &&\
+    find /usr/share/doc -type f -name "*.gz" -delete &&\
+    find /usr/share/doc -type f -name "*.tex" -delete &&\
+    (find /usr/share/doc -type d -empty -delete || true) &&\
+    mkdir -p /usr/share/doc &&\
+    rm -rf /var/cache/apt/archives &&\
+    mkdir -p /var/cache/apt/archives &&\
+    rm -rf /tmp/* /var/tmp/* &&\
+    (find /usr/share/ -type f -empty -delete || true) &&\
+    (find /usr/share/ -type d -empty -delete || true) &&\
+    mkdir -p /usr/share/texmf/source &&\
+    mkdir -p /usr/share/texlive/texmf-dist/source &&\
+
